### ISSUE TITLE
Plot window not in correct aspect ratio

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#215]
The plot window is actually opening in the correct aspect ratio, but I think it's something to do with the minimum font size and how that's being displayed. Would like it to open in the better size window.

![image](https://user-images.githubusercontent.com/101815602/176186029-c22a5747-f4e5-4044-8245-8b4d148adf22.png)

**Comment by bradmartin333** [comment]
This can be resolved by increasing the `Default Plot Window Size` in `Settings` to something like 1200
![image](https://user-images.githubusercontent.com/19335151/176201458-9dc5481f-439c-4fde-9d7b-44beebc0fbbb.png)

Before doing this - I wrote a bunch of autoscaling code and then ran into the same issue with the default plot window size (which works better than more autoscaling due to rounding and padding)
