### ISSUE TITLE
Ctrl Click to ignore all but clicked

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#247]
Can you add Ctrl+Left click on the ignore boxes, to ignore all but the one you just clicked on?
Shift + Left click should cycle between ignore all or un-ignore all.

![image](https://user-images.githubusercontent.com/101815602/201686945-425fb426-dbe2-4a16-b83a-87c45a345f4e.png)

**Comment by riversn** [comment]
![image](https://user-images.githubusercontent.com/101815602/201687107-c5e9c332-f79f-44a7-bfcc-64fc676ae08c.png)

**Comment by bradmartin333** [comment]
ctrl + a + click works like bolding text (selects all if not all selected, deselects all if all selected)

I can add right click menu options to "Select only this" and "Select all but this" - will that work?

**Comment by riversn** [comment]
Ctrl + A should cycle between 'select all' & 'deselect all', you have to also double click the check boxes once selected, not just once.

Ctrl + Left click on a check box to 'check all but this one' is a key feature I would like if possible

**Comment by bradmartin333** [comment]
Ctrl + A = select all (natural binding)
Ctrl + Shift + A = check all
Ctrl + D = deselect all
Ctrl + Shift + D = uncheck all
G = group features (does not apply to criteria)
Shift + G = group redundant features (does not apply to criteria)

I added the right click menu for "all but this" and "only this" in v4.5 - does it have to be control click? I tested ctrl + click and doesn't operate very cleanly. I can try a different way if you need it. It does need to be the only item selected because of the multiselect functionality already implemented.

**Comment by riversn** [comment]
I'll try right clicking and see if that works for me.

**Comment by riversn** [comment]
Ctrl + A should cycle all highlight vs all unhighlight though

**Comment by bradmartin333** [comment]
> Ctrl + A should cycle all highlight vs all unhighlight though

I tried this out - I would have to override `LVN_ITEMCHANGING` and that would most certainly break the app [(Source)](https://objectlistview.sourceforge.net/cs/blog8.html). For instance - I would have to manually program the checkbox to update the `Ignore` or `Pass` property. Right now those properties are bound to the checkbox so there is never a mismatched state.

Ctrl + D is the Photoshop hotkey anyway ;)

**Comment by riversn** [comment]
Ctrl + D makes annoying windows sound when you press it

**Comment by bradmartin333** [comment]
ah okay - I need to add `e.Handled = true;` and/or `e.SuppressKeyPress = true;`
